#+STARTUP: overview
#+TITLE: The Emacs configuration of Tom Rake  
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes
#+OPTIONS: toc:3

This files Emacs.org generates the Emacs startup file init.el
by tangling all the emacs_lisp code blocks.


* Generated Warning at the top of init.el
Add a warning to the beginning of init.el
#+begin_src emacs-lisp
  ;; NOTE: init.el is now generated from Emacs.org.  Please edit that file
  ;;       in Emacs and init.el will be generated automatically!
#+end_src

* Debug init
#+begin_src emacs-lisp
  ;;;; Emacs and init debuging flags
  (setq debug-on-error nil)
  (setq init-file-debug nil)

   ;;;; Control debugging during init
   (when init-file-debug
       (setq use-package-verbose t
             use-package-expand-minimally nil
             use-package-compute-statistics t
             debug-on-error t))
#+end_src
* The multiinitcluster
Each init.el in the multiinitcluster initializes the location of various applications under Emacs.
An application could be a common-lisp implementation like sbcl or ccl.
Or an org-mode application such at GTD.

[[https://github.com/plexus/chemacs2][Chemacs2]] allows separate emacs.d directories to exists which are boot main ~/.emacs.d directory.
Emacs is then started with a --profile=*profile-name*, the chemacs2 profiles are configured in [[~/.emacs-profiles.el]].

A cluster member is referenced by the *system-name*, the *user-login-name* and a chemacs2 *profile-name*.

#+begin_src emacs-lisp
  ;;;; Wider emacs applications may need to locate custom resources.
  ;;;; The various custom configuratiions are collected for the group.
  ;;;; the files at <user-emacs-directory>/multi-init-cluster/<system-name>-<user-login-name>-<chemacs-profile-name>-user-startup.el
  ;;;; Represent all member of the cluster.
  ;;;; the user-emacs-directory and chemacs-profile-names are defined in ~/.emacs-profiles.el
  (message "chemacs-profile-name   : %s" chemacs-profile-name)
  (message "system-name            : %s" system-name)
  (message "user-login-name        : %s" user-login-name)
  (if chemacs-profile-name
      (progn
  	(defvar local-config-name (concat system-name "-" user-login-name "-" chemacs-profile-name "-user-startup")
  	  "The name of local-config file.")
  	(defvar local-config-pathname (concat user-emacs-directory "multi-init-cluster/" local-config-name)
  	  "The filename to load the local-config.")
  	(message "local-config-pathname  : %s" local-config-pathname)
  	(load local-config-pathname))
    (progn
      (message "This config should be executed by chemacs2 and chemacs-profile-name is not defined ")
      (error "Bad chemacs config.")))
  (message "---------- Done with multi-init-cluster startup -------")

#+end_src

* Anaphoric - *it* macros that do-the-right-thing
For various symbol status type execute the body code.

Nothing will be done in the following unless the file exists.

(checksyn-existing-file "/etc/must-exist-file"
   (do-imporatnt-stuff it))

#+begin_src emacs-lisp
  (defmacro checksym-defined (name &rest body)
    "Anaphoric - it macro, where the body can uss *it* when symbol name is defined."
    (let ((_sym (gensym)))
      `(let ((,_sym (intern-soft ,name)))
	 (when ,_sym
	   (let ((it (symbol-value ,_sym)))
	     ,@body)))))

  (defmacro checksym-not-nil (name &rest body)
    "Anaphoric - it macro, where the body can uss *it* when symbol name is defined."
    "Execute the body when the symbol is not nil"
    (let ((_sym (gensym)))
      `(let ((,_sym (intern-soft ,name)))
	 (when (,_sym (symbol-value ,_sym))
	   (let ((it (symbol-value ,_sym)))
	     ,@body)))))

  (defmacro checksym-not-empty-string (name &rest body)
    "Anaphoric - it macro, where the body can uss *it* when symbol name is a string that is not empty."
    (let ((_sym (gensym)))
      `(let ((,_sym (intern-soft ,name)))
	 (when ,_sym
	   (let ((it (symbol-value ,_sym)))
	     (when (and (stringp it) (< 0 (length it)))
	       ,@body))))))


  (defmacro checksym-existing-file (name &rest body)
    "Anaphoric - it macro, where the body can uss *it* when symbol name is a the name of an existing file."
    (let ((_sym (gensym)))
      `(let ((,_sym (intern-soft ,name)))
	 (when ,_sym
	   (let ((it (symbol-value ,_sym)))
	     (when (and (stringp it) (file-exists-p it))
		 ,@body))))))


  (defmacro checksym-existing-directory (name &rest body)
	"Anaphoric - it macro, where the body can us *it* when symbol name is a the name of an existing directory."
    (let ((_sym (gensym)))
      `(let ((,_sym (intern-soft ,name)))
	 (when ,_sym
	   (let ((it (symbol-value ,_sym)))
	     (when (and (stringp it) (file-directory-p it))
		 ,@body))))))

#+end_src

* Does init.el finish?
Setting a flag and clearing it allows testing of init.el completion.
#+begin_src emacs-lisp
  (setq twr/init-loading-flag "default")
  (defun twr/check-init-load ()
    (when twr/init-loading-flag
      (message (concat "INIT DID NOT FINISH!!!!!! " twr/init-loading-flag))))
  (add-hook 'after-init-hook 'twr/check-init-load)
#+end_src
* init.el is autocreated
All the emacs-lisp code blocks in Emacs.org are tangled to build init.el. 
Based on an example from systemcrafters, init.el is created after each save of Emacs.org.
#+begin_src emacs-lisp
  ;; Autommatically tangle our Emacs.org config file when we save it.
  (defun efs/org-babel-tangle-config ()
    "Test if the buffer should be auto-tangled after save"
    ; (message "string-equal: %s %s" (buffer-file-name) (expand-file-name (concat user-emacs-directory "Emacs.org")))
    (when (string-equal (buffer-file-name)
			(expand-file-name "Emacs.org" user-emacs-directory))
      (message "tangle-Emacs.org")

      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
	(org-babel-tangle))))
  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'efs/org-babel-tangle-config)))
#+end_src
* scripts
A number of utilities exacted from Emacs.org have been placed in emacs.d/scripts,
ensure those files are in our load path.
#+begin_src emacs-lisp
  (add-to-list 'load-path (expand-file-name "scripts/" user-emacs-directory))
#+end_src
* Garbage Collection Tweeking
SystemCrafters designed method to tweek garbage collection during and after startup.
#+begin_src emacs-lisp
  (setq gc-cons-threshold (* 50 1000 1000))
#+end_src
* Startup Buffer Choice
I prefer to have the ~/startup-buffer.org opened on emacs launch.
#+begin_src emacs-lisp
  (defun find-first-existing-file (files)
    (if (listp files)
	(if (null files)
	  nil
	  (let ((file (car files)))
	    (if (and file (file-exists-p file))
	      file
	      (find-first-existing-file (cdr files)))))
      (error "files should be a list but is %s" files)))
    (setq initial-buffer-choice
	  (find-first-existing-file (list "~/startup-buffer.org"
					   (concat user-emacs-directory "startup-buffer.org"))))
#+end_src
* Default Coding System
Setup various language, coding-systems, this was to fix a number of problems a long time ago.

#+begin_src emacs-lisp
  ;; UTF-8 as default encoding
  (set-language-environment "UTF-8")
  (set-default-coding-systems 'utf-8)
  (set-keyboard-coding-system 'utf-8-unix)

  ;; do this especially on Windows, else python output problem
  (set-terminal-coding-system 'utf-8-unix)  
#+end_src
* Report Startup Time
Monitor and report emacs startup time.
#+begin_src emacs-lisp
    ;;;; Reporting Startup Time
  (defun efs/display-startup-time ()
    (message "Emacs loaded in %s with %d garbage collections."
  	     (format "%.2f seconds"
  		     (float-time
  		      (time-subtract after-init-time before-init-time)))
  	     gcs-done))

  (add-hook 'emacs-startup-hook #'efs/display-startup-time)
#+end_src
* Straight Package manager
This is the straight.el boilerplate startup code.
#+begin_src emacs-lisp
  ;;;; straight boilerplate startup code.
    (defvar bootstrap-version)
      (let ((bootstrap-file
             (expand-file-name
              "straight/repos/straight.el/bootstrap.el"
              (or (bound-and-true-p straight-base-dir)
                  user-emacs-directory)))
            (bootstrap-version 7))
        (unless (file-exists-p bootstrap-file)
          (with-current-buffer
              (url-retrieve-synchronously
               "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
               'silent 'inhibit-cookies)
            (goto-char (point-max))
            (eval-print-last-sexp)))
        (load bootstrap-file nil 'nomessage))

  ;;;; Various straight customizations.
      (straight-use-package 'use-package)
      (straight-use-package '(org :type built-in))
      (straight-use-package 'htmlize)
#+end_src
* use-package
Use-package is the central component I use to weave my init.el.
Emacs comes with use-package.
So I merely need to require it.
  #+begin_src emacs-lisp
    ;;;; use-package
    (require 'use-package)
    (setq straight-use-package-by-default t)
    (setq use-package-verbose t)
    (setq use-package-always-defer t)

#+end_src

* Conversion of .org files in emacs.d/
org files in emacs.d can be tangled to .el files and then loaded.
This is an older mechanism and may not be currently used.

#+BEGIN_SRC emacs-lisp
  ;;;; Macro to load user customizations from .emacs.d
  (defmacro local-custom-file (file description)
    `(progn
       ;(require 'org)
       ;;(message (concat "Looking for " ,description " file: " ,file ))
       (let ((file-and-path (expand-file-name ,file user-emacs-directory)))
	 (if (file-exists-p file-and-path)
	     (progn ;;(message (concat "org-babel-load of " file-and-path))
	            (require 'org)
		    (org-babel-load-file file-and-path))
	   (message (concat "Custom file is missing " file-and-path))))))

#+END_SRC
* Magic Modes
Magic modes turn files with a given extension to use a specific emacs mode.

#+BEGIN_SRC emacs-lisp
  ;;;; Magic File modes
  (setq magic-mode-alist '(("*.org" . org)))
#+END_SRC
* Basic Look and feel
Change how emacs generally works startup screen, bell, toolbar and file dialogs.

#+BEGIN_SRC emacs-lisp
  ;;;; Have a clean statup screen
  (setq inhibit-startup-screen t)
  (setq visible-bell 1)
   ;;;; Turn off tool bar
  (tool-bar-mode 0)
  (setq use-file-dialog nil)
#+END_SRC
* Fix Windows 10 cursor problem
This is for an old  cursor workaround.
 #+BEGIN_SRC emacs-lisp
   (when (equal system-type 'windows-nt)
     (setq w32-use-visible-system-caret nil))
 #+END_SRC

* Buffer Auto reverting
#+BEGIN_SRC emacs-lisp
  ;;;; auto revert mode
  (global-auto-revert-mode 1)

  ;;;; dired auto revert
  (setf global-auto-revert-non-file-buffers t)
#+END_SRC
* IDO
#+BEGIN_SRC emacs-lisp
(use-package  ido
    :config
  (ido-mode t))
#+END_SRC
* Which-Key
#+begin_src emacs-lisp
  (use-package which-key
    :straight t)
#+end_src
* Vertico
This is recommended setup from  [[https://github.com/minad/vertico]]
I have the following issues
- I want the list resized when windows is resized
- I want the items sorted alpha, directories at the top.
  [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Programmed-Completion.html]]
    - display-sort-function
    - completion-table-dynamic ???
Read up on [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion.html]]
#+begin_src emacs-lisp
  ;;;; Enable vertico
  (use-package vertico
    :straight t
    :init
    (vertico-mode))

  (use-package savehist
    :init
    (savehist-mode))
#+end_src
* Obsidian
See  the source repo at [[https://github.com/licht1stein/obsidian.el]]
To use this package you must define 
#+begin_src emacs-lisp :tangle no
  (defun obsidian-opinonated-directories (base)
    (obsidian-specify-path base)
    (setf obsidian-inbox-directory "Inbox")
    (setf obsidian-daily-notes-directory "Daily Notes")
    (setf obsidian-template-directory "Templates"))

  (use-package obsidian
    :straight t
    :demand t
    :config
    ;(obsidian-specify-path config-obsidian-specify-path)
    (obsidian-opinonated-directories config-obsidian-specify-path)
    (global-obsidian-mode t)
    :bind (:map obsidian-mode-map
		;; Replace C-c C-o with Obsidian.el's implementation. It's ok to use another key binding.
		("C-c C-o" . obsidian-follow-link-at-point)
		;; Jump to backlinks
		("C-c C-b" . obsidian-backlink-jump)
		;; If you prefer you can use `obsidian-insert-link'
		("C-c C-l" . obsidian-insert-wikilink)))
#+end_src
* Ispell configured with Aspell
aspell configuration is in [[~/.aspell.conf]]
Fixed on 7/2/2022 moving to DESKER
[2022-10-07 Fri 18:12]
  - The EOL of the .aspell configuration files got corrupted.
  - They should all be Unix (LF) ends of lines.
#+BEGIN_SRC emacs-lisp
  (setq ispell-program-name "aspell")
#+END_SRC
* JAVA Interface
Certain tools need java set that location here.
#+begin_src emacs-lisp
    ;; The java interface assumption is you can execute the program "java"
    ;; There is no jdk to be considered.
    (defvar java-executable (executable-find "java")
      "The java-executable to use for java.")
#+end_src
* lsp mode
#+begin_src emacs_lisp
(use-package lsp-mode
  :init
  ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
  (setq lsp-keymap-prefix "C-c l")
  :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
         (XXX-mode . lsp)
         ;; if you want which-key integration
         (lsp-mode . lsp-enable-which-key-integration))
  :commands lsp)
#+end_src
* lsp-ls-plus

From: [[https://www.reddit.com/r/emacs/comments/1sp1wly/launching_a_new_grammarspell_checking_tool_for/]] How to get quickly started.
- commented out :vc line
- removed comment from :straignt line

Error :custom was empty

- removed comment from the three :custom lines

Error: [lsp-ltex-plus] Aborting: ltex-ls-plus not found on PATH.  See installation instructions at https://github.com/alberti42/emacs-ltex-plus/#server-installation or set ‘lsp-ltex-plus-ls-plus-executable’ to the absolute path of the binary.

THIS IS THE END OF How to get quickly started.

I installed ltex-ls in emacs.d
I added lsp mode section.
I configured the lsp-ltex-ls-plus-executable and added various :config items.

I now want to univeralize this to a windows version.
#+begin_src emacs-lisp
  (defvar ltex-ls-plus-base   (concat user-emacs-directory "ltex-plus/ltex-ls-plus-18.6.1/"))
  (defvar ltex-ls-plus-bin   (concat ltex-ls-plus-base "bin/ltex-ls-plus"))
  (use-package lsp-ltex-plus
    :if (file-exists-p ltex-ls-plus-bin)
    ;; For Emacs 29+, use the built-in :vc fetcher:
    ;; :vc (:url "https://github.com/alberti42/emacs-ltex-plus")

    ;; If you prefer straight.el, replace the :vc line above with this:
    :straight (lsp-ltex-plus :type git :host github :repo "alberti42/emacs-ltex-plus")

    :defer t

    :custom
    (lsp-ltex-plus-ltex-ls-path ltex-ls-plus-base)
    (lsp-ltex-plus-language "en-US")
    (lsp-ltex-plus-ls-plus-executable ltex-ls-plus-bin)
    ;; To use the online service, set the URI.
    ;; If you prefer the remote server (slower, but more precise), uncomment the next line (it defaults to nil).
    ;; (lsp-ltex-plus-lt-server-uri "https://api.languagetoolplus.com")
    ;; Uncomment the next line to also check grammar in the comments of programming
    ;; languages (Python, C, Rust, …) in addition to markup formats (LaTeX, Markdown, Org, …).
    (lsp-ltex-plus-check-programming-languages t)
    
    ;; Uncomment to apply the "Kind-First" protocol patch to lsp-mode.
    ;; Strongly recommended, especially if you use a remote LanguageTool server;
    ;; the network latency makes JSON-RPC ID collisions between client and server
    ;; requests almost inevitable, which can permanently stall the connection.
    ;; The patch is a general lsp-mode fix and benefits every LSP client, not
    ;; only ltex-ls-plus. Details: https://github.com/alberti42/emacs-ltex-plus#lsp-mode-protocol-patch
    (lsp-ltex-plus-apply-kind-first-patch t)

    :init
    (lsp-ltex-plus-enable-for-modes))
#+end_src
* Joining items as strings with and without quoting
#+BEGIN_SRC emacs-lisp
(require 'quoting-tools)
#+END_SRC
* Ensure gnu-tools
gunk
#+begin_src emacs-lisp
  (when (equal system-type "windows-nt")
    (require 'gnu-tools))
#+end_src
* Magit
#+BEGIN_SRC emacs-lisp
  ;;;; Magit 
  (use-package magit
    ;:defer 2
    :straight t
    ;:pin melpa
    :bind
     (("C-x g" . magit-status)
      ("C-x M-d" . magit-dispatch-popup)))
 #+END_SRC
* SSH Agency
#+BEGIN_SRC emacs-lisp
  ;;;; SSH Agency
  (use-package ssh-agency
  :straight t
  :init
  (setenv "GIT_ASKPASS" "git-gui--askpass")
  (setenv "SSH_ASKPASS" "git-gui--askpass")
  :after (magit))
#+END_SRC
* Modus Theme Configuration
Main Page: [[https://protesilaos.com/emacs/modus-themes]]
#+BEGIN_SRC emacs-lisp
  (use-package modus-themes
    :ensure t
    :init
    (set-face-attribute 'default nil :height 150)
	;; Subtle red background, red foreground, invisible border

    (setq modus-themes-region '(bg-only))
    (setq modus-themes-paren-match '(bold intense))
    (setq modus-themes-lang-checkers '(background intense))
    (setq modus-themes-italic-constructs t)
    (setq modus-themes-bold-contructs t)
    (setq modus-themes-prompts  '(bold italic))
    ;; Subtle blue background, neutral foreground, intense blue border
    (setq modus-themes-common-palette-overrides
      '((bg-mode-line-active bg-blue-subtle)
	(fg-mode-line-active fg-main)
	(border-mode-line-active blue-intense)))
    (setq modus-themes-mode-line '(accented borderless))
    ;;; Org Mode
    (setq modus-themes-heading
	  `((1 . (rainbow bold intense 2.3))
	    (2 . (rainbow bold intense 1.9))
	    (3 . (rainbow bold intense 1.7))
	    (4 . (rainbow bold intense 1.5))
	    (5 . (rainbow bold intense 1.3))
	    (6 . (rainbow bold intense 1.1))
	    (t . (rainbow bold background 1.0))))
    (setq modus-themes-org-agenda
	  '((header-block . (variable-pitch 1.5))
	    (header-date . (grayscale workaholic bold-today 1.2))
	    (event . (accented italic varied))
	    (scheduled . uniform)
	    (habit . traffic-light)))
    (setf custom-safe-themes "e410458d3e769c33e0865971deb6e8422457fad02bf51f7862fa180ccc42c032")
    (load-theme 'modus-vivendi t))
#+END_SRC

* Rainbow Delimeters
#+BEGIN_SRC emacs-lisp
  ;;;; rainbow-delimiter
  (use-package rainbow-delimiters)
#+END_SRC

* Powershell
#+begin_src emacs-lisp
  ;;;; powershell
  (defun powershell()
    (interactive)
    (let ((explicit-shell-file-name "powershell.exe")
	  (explicit-powershell.exe-args '()))
      (shell (generate-new-buffer-name "*powershell*"))))
#+end_src
* Shells
  [TBD] Decide what is CRUFF here.
  I am attempting to use the friendly-shell infrastructure.

  shell/git-bash works but has prompt problems.
[2023-05-19] Stop tangle of this code.
#+begin_src emacs-lisp
  ;;;; Set the explicit shell name to msys2 version.
  (when (or (equal system-type "windows-nt"))
    (setq explicit-shell-file-name "c:/devel/msys64/usr/bin/bash"))
#+end_src
* Eshell
#+begin_src emacs-lisp
  
  ;;;; eshell this really  msys2 path stuff.
  (when (or (equal system-type "windows-nt"))
    (setenv  "PATH" (concat
  		   (list
  		    "C:/devel/msys64/ucrt64/bin" ";"
  		    "C:/devel/msys64/bin" ";")
  		   (getenv "PATH"))))
#+end_src
* Add shell extensions
[TBD] If this is org shell extenstion then put this in org-mode section.
#+BEGIN_SRC emacs-lisp
(use-package shx
  :straight t)
#+END_SRC
* Tramp
Make plink the default tramp method if running on Windows when plink.exe exists.
#+BEGIN_SRC emacs-lisp
  (use-package tramp
    :config
      (when (equal  system-type "windows-nt")
  	(setq putty-directory "c:/Program Files/PuTTY/")
  	(setq tramp-default-method "plink")
  	(when (and (not (string-match putty-directory (getenv "PATH")))
  		   (file-directory-p putty-directory))
  	  (setenv "PATH" (concat putty-directory ";" (getenv "PATH")))
  	  (add-to-list 'exec-path putty-directory)))
      (when (equal system-type "gnu/linux")
        (message "Tramp GNU/Linux Config")))
#+END_SRC
* Paredit mode
  #+BEGIN_SRC emacs-lisp
    (use-package paredit
      :straight t
      :hook (lisp-mode . enable-paredit-mode))
    #+END_SRC
* Easy-Hugo
Use emacs-easy-hugo.
#+begin_src emacs-lisp
  (use-package easy-hugo
  :straight t
  :custom
  (easy-hugo-basedir "C:/Users/zzzap/Documents/Code/source-projects/ACTIVE/tomrake.github.io/")
  (easy-hugo-postdir "content/blog/")
  )
#+end_src
* Report Debug START COMMONLISP STUFF                              :noexport:
Print Debug markers in *messages*
#+BEGIN_SRC emacs-lisp :eval never-export
(message "Debug <<<<<<<<< START COMMONLISP STUFF")
#+END_SRC
* Common Lisp mode slime or sly
#+BEGIN_SRC emacs-lisp
  (defvar common-lisp-mode-tool :slime "This can be :slime or :sly.")

#+END_SRC
* Taging of Inferior Invokers
Create a windows standalone startup for a lisp version.
#+BEGIN_SRC emacs-lisp
    (defvar my-lisp-implementations nil
	"For various implemenations there are lisp invokers for slime and sly.")

    (defmacro assemble-invoker (my-tag program program-args environment)
       "The format of a standard slime entry for a lisp implenatation."
       `(list ,my-tag (cons ,program ,program-args) :env ,environment))

  ;;;; [TBD] Replace the assemble invokers with an optional program-args and enviroment 
    (defun make-lisp-invoker (tag program &optional program-args environment)
      `(,tag ,(cons ,program  ,program-args) ,(if environment (list :env environment))))

    (defmacro assemble-invoker-no-env (my-tag program program-args environment)
      "The format of a standard slime entry for a lisp implenatation."
      `(list ,my-tag (cons ,program ,program-args)))


    (defun collect-this-lisp (lisp-invoker)
	"Add an specific lisp invoker to slime list"
	(add-to-list 'my-lisp-implementations lisp-invoker))
#+END_SRC

* SBCL  Invoker 
Start all SBCL lisps with a --noinform argument and standart arguments.
#+BEGIN_SRC emacs-lisp
  ;;;; The standard options for SBCL
  (setq sbcl-program-arguments '("--dynamic-space-size" "4000" "--noinform"))

  (defun assemble-sbcl-enviroment-invoker (my-tag program environment)
    (assemble-invoker my-tag program sbcl-program-arguments environment))
#+END_SRC

I collect all sbcl version of lisp from a base directory which is structured

- local-config-sbcl-location
  - version
    - name
      - .production  - need to be collected unless name is 'production'
      - bin
      - config
      - lib

	
#+BEGIN_SRC emacs-lisp
    (defun get-sbcl-versions (base-address)
      "Get all the directories under the base-address"
      (remove "." (remove ".." (directory-files  base-address ))))

    (defun get-sbcl-configs (version-address)
      (remove "." (remove ".." (directory-files version-address))))

    (defun assemble-named-sbcl-version (prefix base-address version config)
      "Create a SBCL invoker for specific compiled version."
      (assemble-sbcl-enviroment-invoker
       (intern (concat prefix version "-" config))
       (concat base-address "/" version "/" config (sbcl-exe))
       (list (concat "SBCL_HOME=" base-address "/" version "/" config "/lib/sbcl/"))))

  (defun augment-versions (vers)
    "Add the numeric version  pieces to each element."
    (let ((aug-vers 
	   (mapcar (lambda (v)
	      (cons v (mapcar
		       (lambda (s) (string-to-number s)) (split-string v "\\." ))))
		   vers)))
      aug-vers))

   (defun sort-by-nth (n aug-vers)
     "sort the aug-vers by the nth item"
     (sort aug-vers (lambda (a b) ( < (nth n a) (nth n b)))))

    (defun filter-non-versions (l)
      "Remove any string from the list that container other that 0-9 or ."
      (seq-filter (lambda (a) (not (string-match "[^0-9.]" a))) l))

    (defun sort-version (vers)

      (mapcar (lambda (av)  (car av))
	      (sort-by-nth 1 (sort-by-nth 2 (sort-by-nth 3 (augment-versions (filter-non-versions vers)))))))


    (defun sbcl-exe ()
      (if (string-equal system-type "windows-nt")
	  "/bin/sbcl.exe"
	  (if (string-equal system-type "gnu/linux")
	      "/bin/sbcl"
	      (error "Unknown system type"))))


    (defun add-win64-sbcl (base-address)
      "Add a SBCL invoker for all versions under the base-address"
      (let ((versions (sort-version (get-sbcl-versions base-address))))
	(message "versions: %s"versions)
	(dolist (version versions)
	  (let ((configs (get-sbcl-configs (concat base-address "/" version))))
	    (dolist (config configs)
	      (when (and (file-exists-p (concat base-address "/" version "/" config  (sbcl-exe)))
			 (or (string= config "production") (file-exists-p (concat base-address "/" version "/" config "/.production"))))
		(collect-this-lisp (assemble-named-sbcl-version "sbcl64-" base-address version config))))))))

    (defun collect-sbcl ()
      "Add all the slime invokers for SBCL 64bit compiled versions."
      (checksym-existing-directory "local-config-sbcl-location"
		(add-win64-sbcl it)))
#+END_SRC
* CCL Invokers

Clozure Common Lisp from [[https://ccl.clozure.com/]]

#+BEGIN_SRC emacs-lisp
  (defun ccl-invoker (my-tag path)
    "Return a lisp invoker; nil if path does not exist"
      (when (file-exists-p path)
	`(,my-tag (,path))))

  (defun add-ccl ()
    "Collect any CCL Lisp versions"
    (checksym-existing-file "local-config-ccl32-location" (collect-this-lisp (ccl-invoker 'ccl-32 it)))
    (checksym-existing-file "local-config-ccl64-location" (collect-this-lisp (ccl-invoker 'ccl-64 it))))	  
#+END_SRC

* ABCL

Supporting the Right to Arm Bears!

Armed Bear Common Lisp from  [[https://www.abcl.org/doc/abcl-user.html]]

I need to check that there is a java and 

#+BEGIN_SRC emacs-lisp
  (defun invoke-abcl()
    "Return a lisp invoker; nil if abcl is not found,"
    (let ((abcl local-config-abcl-location))
      (when (file-exists-p abcl)
	`(abcl  ,(list java-executable "-jar" abcl)))))

  (defun add-abcl ()
    "Check of abcl implmentations"
    (let ((has-java (checksym-existing-file "java-executable" it)))
      (when has-java
	(checksym-existing-file "local-config-abcl-location"
				(collect-this-lisp `(abcl ,(list has-java "-jar" it)))))))
#+END_SRC

* Report Debug START GATHERING INVOKERS                            :noexport:
Print Debug markers in *messages*
#+BEGIN_SRC emacs-lisp :eval never-export
(message "Debug  START GATHERING INVOKERS")
#+END_SRC
* Collect Lisp Invokers
The lisp invokers are slime/sly additions to their implemenations lists.
The collect-lisp-invokers function returns a list of all those invokers for use by slime and sly.

#+BEGIN_SRC emacs-lisp
  (defun collect-lisp-invokers ()
      "collect all lisp-invokers to my-lisp-implementations."
    (setf my-lisp-implementations nil)
    (add-abcl)
    (add-ccl)
    (collect-sbcl)
    my-lisp-implementations)

#+END_SRC
* Report Debug SLIME MARK                                          :noexport:
Print Debug markers in *messages*
#+BEGIN_SRC emacs-lisp :eval never-export
(message "Debug SLIME MARK")
#+END_SRC
* SLIME
These are issues about slime.
Many of the things I use for slime acually require slime. This is true for slime-repl-ansi-color
#+begin_src emacs-lisp
    (use-package slime-repl-ansi-color
    :straight t
    :defer t)
#+end_src
#+begin_src emacs-lisp
  (use-package slime
    :if (eq common-lisp-mode-tool :slime)
    :straight t
    :config
    (when (equal system-type 'gnu/linux)
      (message "Linux Slime")
      (defvar slime-lisp-location nil)
      (when (file-exists-p local-config-sbcl-location)
  	(setq slime-lisp-location local-config-sbcl-location))
      (unless slime-lisp-location
        (setq slime-lisp-location "sbcl"))
      (setq inferior-lisp-program slime-lisp-location)

     
      (require 'slime-repl-ansi-color)
      (add-hook 'slime-repl-mode-hook
  	      #'(lambda () (setf slime-repl-ansi-color-mode 1))))
    (when (equal system-type 'windows-nt)
      (message "Windows Slime.")
      (setf slime-lisp-implementations (collect-lisp-invokers))
      (require 'slime-repl-ansi-color)
      (add-hook 'slime-repl-mode-hook
      	      #'(lambda () (setf slime-repl-ansi-color-mode 1)))))
#+end_src


* SLY
SLY is disabled my the :tangle nil in the below items.
#+begin_src emacs-lisp :tangle nil
  (use-package sly-repl-ansi-color
  :straight t
  :defer t)
#+end_src
#+BEGIN_SRC emacs-lisp :tangle nil
  (use-package sly
    :disabled
    :if (eq common-lisp-mode-tool :sly)
    :straight t
    :defer t
    :init
    (setq sly-lisp-implementations (collect-lisp-invokers))
    :config
    (require 'sly-repl-ansi-color)
    (push 'sly-repl-ansi-color sly-contribs))
#+END_SRC
* Report Debug SLIME END MARK                                      :noexport:
Print Debug markers in *messages*
#+BEGIN_SRC emacs-lisp :eval never-export
(message "Debug SLIME END MARK")
#+END_SRC
* Enable lisp-mode .lisp and .asd files
  #+BEGIN_SRC emacs-lisp
    (setq auto-mode-alist
    	(append '((".*\\.asd\\'" . lisp-mode))
    		auto-mode-alist))

    (setq auto-mode-alist
    	(append '((".*\\.cl\\'" . lisp-mode))
    		auto-mode-alist))

    (setq auto-mode-alist
          (append '((".*\\.rkt\\'" . racket-mode))
    	      auto-mode-alist))
  #+END_SRC

* Common Lisp HyperSpec
  I use my local clone of the Hyperspec
* Hyperspec Root is loaded from Enviroment location
  #+BEGIN_SRC emacs-lisp
    (when (getenv "HyperSpec")
     (setq common-lisp-hyperspec-root (convert-standard-filename (getenv "HyperSpec"))))
  #+END_SRC
* dap-mode
#+begin_src emacs-lisp
  (straight-use-package 'dap-mode)

  (use-package dap-mode
   :straight t
   :config
   (dap-auto-configure-mode))
  
#+end_src
* tree-sitter
#+begin_src emacs-lisp
  (use-package treesit-auto
    :straight t
    :config
      (treesit-auto-add-to-auto-mode-alist 'all)
    (global-treesit-auto-mode))
#+end_src
* Racket
#+begin_src emacs-lisp   
  (use-package racket-mode
    :straight t
    ;:config
    ;(setf racket-program "C:/Program Files/Racket/Racket.exe" )
  )
#+end_src
* Zotxt-emacs
#+begin_src emacs-lisp
  (use-package deferred
    :straight t)
  (use-package request
    :straight t)
  (use-package zotxt
  :straight t
  :after (request deferred))
#+end_src
* Pascal Setup
  [TBD] I have no pascal compiler configured.
#+BEGIN_SRC emacs-lisp
(add-hook 'pascal-mode-hook
	  (lambda ()
	    (set (make-local-variable 'compile-command)
		 (concat "fpc " (file-name-nondirectory (buffer-file-name)))))
	  t)

(setq auto-mode-alist
      (append '((".*\\.pas\\'" . pascal-mode))
	      auto-mode-alist))

(setq auto-mode-alist
      (append '((".*\\.pp\\'" . pascal-mode))
	      auto-mode-alist))

(setq auto-mode-alist
      (append '((".*\\.yml\\'" . yaml-mode))
	      auto-mode-alist))
#+END_SRC

* simple httpd
Use simple-httpd to preview a site from emacs.
#+begin_src emacs-lisp
  (use-package simple-httpd
    :straight t)
#+end_src
* PS Print with GHOSTSCRIPT
#+BEGIN_SRC emacs-lisp
	  ;;;; PS Print with GHOSTSCRIPT
  (when (eq system-type 'windows-nt)
	    (setq ps-lpr-command "C:/Program Files/gs/gs9.56.1/bin/gswin64c.exe")
	    (setq ps-lpr-switches '("-q" "-dNOPAUSE" "-dBATCH" "-sDEVICE=mswinpr2" "-sOutputFile=\"%printer%Canon\ TS6000\ series\""))
	    (setq ps-printer-name t))
  (setf ps-font-family 'Courier)
  (setf ps-font-size 10.0)
  (setf ps-line-number t)
  (setf ps-line-number-font-size 10)

  (defun ps-portrait-one-column()
    (interactive)
    (setq ps-landscape-mode nil)
    (setq ps-number-of-columns 1))

  (defun ps-landscape-one-column()
    (interactive)
    (setq ps-landscape-mode t)
    (setq ps-number-of-columns 1))
#+END_SRC

* Emacs Backup Files
;;;; Emacs Backup Files
#+begin_src emacs-lisp
(setq backup-directory-alist `(("." . ,(expand-file-name "tmp/backups/" user-emacs-directory))))
#+end_src

* Eshell
#+begin_src emacs-lisp
  (defun efs/configure-eshell ()
	   ;; Save command history when commands are entered
	   (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)

	   ;; Truncate buffer for performance
	   (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)

	   (setq eshell-history-size         10000
		 eshell-buffer-maximum-lines 10000
		 eshell-hist-ignoredups t
		 eshell-scroll-to-bottom-on-input t))

  (use-package eshell
	   :hook (eshell-first-time-mode . efs/configure-eshell))

  (use-package eshell-git-prompt
    :straight t
    :config
      (eshell-git-prompt-use-theme 'powerline))
#+end_src
* Report Debug START                                               :noexport:
Print Debug markers in *messages*
#+BEGIN_SRC emacs-lisp :eval never-export
(message "Debug START")
#+END_SRC

* Dired
** all-the-icons-dired
#+begin_src emacs-lisp
  (use-package dired
    :straight nil
    :after all-the-icons-dired)

  (use-package all-the-icons-dired
    :straight t
    :after all-the-icons)
  
   (add-hook 'dired-mode-hook 'all-the-icons-dired-mode)
#+end_src

** Single Dired buffer
#+begin_src emacs-lisp
  (use-package dired-single
    :straight nil
    :after
      dired
    :config
      (defun twr/dired-init ()
	(define-key dired-mode-map [remap dired-find-file]
	  'dired-single-buffer)
	(define-key dired-mode-map [remap dired-mouse-find-file-other-window]
	  'dired-single-buffer-mouse)
	(define-key dired-mode-map [remap dired-up-directory]
	  'dired-single-up-directory))
      (twr/dired-init)
      (setq dired-single-use-magic-buffer t)
      ;; F5 is my special key
      (global-set-key [(f5)] 'dired-single-magic-buffer)
      (global-set-key [(control f5)] (function
	(lambda nil (interactive)
	  (dired-single-magic-buffer default-directory))))
      (global-set-key [(shift f5)] (function
	(lambda nil (interactive)
	  (message "Current directory is: %s" default-directory))))
      (global-set-key [(meta f5)] 'dired-single-toggle-buffer-name))
#+end_src
** File Sort Order
#+begin_src emacs-lisp
  (defun mydired-sort ()
	  "Sort dired listings with directories first."
	  (save-excursion
	    (let (buffer-read-only)
	      (forward-line 2) ;; beyond dir. header 
	      (sort-regexp-fields t "^.*$" "[ ]*." (point) (point-max)))
	    (set-buffer-modified-p nil)))

  (defadvice dired-readin
	  (after dired-after-updating-hook first () activate)
	  "Sort dired listings with directories first before adding marks."
	  (mydired-sort))
#+END_SRC
* Report Debug TEST                                                :noexport:
Print Debug markers in *messages*
#+BEGIN_SRC emacs-lisp  :eval never-export
(message "Debug TEST - YES!!!")
#+END_SRC
 

* Mastodon
#+begin_src emacs-lisp
;;;; mastodon
  (use-package mastodon
    :straight t)
  (setq mastodon-active-user "tomrake")
  (setq mastodon-instance-url "https://mastodon.social")
#+end_src
* Openwith
NOTE:
On Windows 11, this only opens the file by the Windows extension
So configure it there.
#+begin_src emacs-lisp
  (when (require 'openwith nil 'noerror)

     (setq openwith-associatsions
	 (list (list (openwith-make-extension-regexp '("mpg" "mpeg" "mp3" "mp4"
					      "avi" "wmv" "wav" "mov" "flv"
					      "ogm" "ogg" "mkv")) "vlc.exe")
	       (list (openwith-make-extension-regexp '("JPEG" "JPG"))
		     "c:/Program Files (x86)/JPEGView/JPEGView.exe" '(file))))
;;    (message "OPENWITH CONFIG")
;;    (message openwith-associatsions)
    (openwith-mode 1))
#+end_src
* Recentf 
#+begin_src emacs-lisp
(require 'recentf)
(recentf-mode 1)
(setq recentf-max-menu-items 25)
(global-set-key "\C-x\ \C-r" 'recentf-open-files)
#+end_src
* YAML Mode
Add yaml mode
#+begin_src emacs-lisp
(use-package yaml-mode)
#+end_src
* JSON to Single line
This was found on https://stackoverflow.com/questions/39861580/emacs-program-to-collapse-json-to-single-line and is Justin Schell response.

I am using to add icons to the icons.json file derived from feathericons.
#+begin_src emacs-lisp
(defun json-to-single-line (beg end)
  "Collapse prettified json in region between BEG and END to a single line"
  (interactive "r")
  (if (use-region-p)
      (save-excursion
        (save-restriction
          (narrow-to-region beg end)
          (goto-char (point-min))
          (while (re-search-forward "[[:space:]\n]+" nil t)
            (replace-match " "))))
    (print "This function operates on a region")))
#+end_src
* load per user settings
 #+BEGIN_SRC emacs-lisp
   ;;;; Various user settings is a local configuration.
   (local-custom-file "local-settings.org" "Final user settings")
 #+END_SRC

 
* Sourcing of Scripts
#+BEGIN_SRC emacs-lisp
(require 'filename2clipboard)
#+END_SRC
* ERC
#+begin_src emacs-lisp
  (use-package erc
      :straight t
      :config
      (setq erc-fill-column 120
	erc-fill-function 'erc-fill-static
	erc-fill-static-center 20))

  (use-package erc-hl-nicks
    :straight t
    :after erc
    :config
    (add-to-list 'erc-modules 'hl-nicks))

  (use-package erc-hl-nicks
    :straight t
    :after erc
    :config
    (add-to-list 'erc-modules 'hl-nicks))

  (use-package emojify
    :straight t
    :hook (erc-mode . emojify-mode)
    :commands emojify-mode)

#+end_src
* EMMS
I may need to recompile emacs again to fix this.
#+begin_src emacs-lisp
  (use-package emms
    :straight t
    :if (eq system-type 'gnu/linux)
    :config
    (emms-all)
    (setq emms-player-list '(emms-player-vlc)
  	emms-info-functions '(emms-info-native)))
#+end_src

* vterm
#+begin_src emacs-lisp
  (use-package vterm
    :straight t
    :commands vterm
    :config
    (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *")
    ;;(setq vterm-shell "zsh")
    (setq vterm-max-scrollback 10000))
#+end_src
* pico
#+begin_src emacs-lisp
(load "pico-emacs")
#+end_src
* Deactivated code related to cmake-ide
** Flycheck                                                        :noexport:
#+begin_src emacs-lisp :tangle no
	(use-package flycheck
	  :straight t
	  :config
	  (add-hook 'c++-mode-hook 'flycheck-mode)
	  (add-hook 'c-mode-hook 'flycheck-mode)
	  (add-hook 'flycheck-mode-hook #'flycheck-irony-setup))
					    ;
	  ;; (global-flycheck-mode +1)
	  ;; (add-hook 'after-init-hook #'global-flycheck-mode)
	(use-package flycheck-rtags
	  :after (flycheck rtags)
	  :config
	  (defun my-flycheck-rtags-setup ()
	    (flycheck-select-checker 'rtags)
	    (setq-local flycheck-highlighting-mode nil) ;; RTags creates more accurate overlays.
	    (setq-local flycheck-check-syntax-automatically nil))
	  ;; c-mode-common-hook is also called by c++-mode
	  (add-hook 'c-mode-common-hook #'my-flycheck-rtags-setup))

  #+end_src
** helm                                                            :noexport:
#+begin_src emacs-lisp  :tangle no
  (use-package helm
  :straight t
  )
#+end_src
** rtags                                                           :noexport: 
#+begin_src emacs-lisp  :tangle no
  (use-package rtags
    :straight t
    :after helm
   :hook (c++-mode . rtags-start-process-unless-running)
  :config (setq rtags-completions-enabled t
		rtags-path "/home/zzzap/Documents/Emacs-Configs/production/emacs.d/straight/repos/rtags/src/rtags.el"
		rtags-rc-binary-name "/usr/local/bin/rc"
		rtags-use-helm t
		rtags-rdm-binary-name "/usr/local/bin/rdm")
  :bind (("C-c E" . rtags-find-symbol)
	 ("C-c e" . rtags-find-symbol-at-point)
	 ("C-c O" . rtags-find-references)
	 ("C-c o" . rtags-find-references-at-point)
	 ("C-c s" . rtags-find-file)
	 ("C-c v" . rtags-find-virtuals-at-point)
	 ("C-c F" . rtags-fixit)
	 ("C-c f" . rtags-location-stack-forward)
	 ("C-c b" . rtags-location-stack-back)
	 ("C-c n" . rtags-next-match)
	 ("C-c p" . rtags-previous-match)
	 ("C-c P" . rtags-preprocess-file)
	 ("C-c R" . rtags-rename-symbol)
	 ("C-c x" . rtags-show-rtags-buffer)
	 ("C-c T" . rtags-print-symbol-info)
	 ("C-c t" . rtags-symbol-type)
	 ("C-c I" . rtags-include-file)
	 ("C-c i" . rtags-get-include-file-for-symbol)))
(setq rtags-display-result-backend 'helm)
#+end_src
** company                                                         :noexport:
#+begin_src emacs-lisp  :tangle no
  (use-package company
  :straight t
  :config
  (add-to-list company-backends 'company-rtags))
  #+end_src
** cmake-ide                                                       :noexport:
#+begin_src emacs-lisp  :tangle no
   (use-package cmake-ide
     :straight t
     :after (rtags company-rtags)
     :config
  ;   (setq rtags-completetions-enabled t)
  ;   (setq rtags-autostart-diagnostics t)
  ;   (rtags-enable-standard-keybinding)
     (cmake-ide-setup)
     (add-hook 'c-mode-hook . rtags-start-process-unless-running)
     (add-hook 'c++-mode . rtags-start-process-unless-running))
     #+end_src
**  Irony                                                          :noexport:
#+begin_src emacs-lisp :tangle no
    (use-package irony
    :straight t
    :config
    (add-hook 'c++-mode-hook 'irony-mode)
    (add-hook 'c-mode-hook 'irony-mode)
    (add-hook 'objc-mode-hook 'irony-mode)

    (defun my-irony-mode-hook ()
      (define-key irony-mode-map [remap completion-at-point]
	'irony-completion-at-point-async)
      (define-key irony-mode-map [remap complete-symbol]
	'irony-completion-at-point-async))

    (add-hook 'irony-mode-hook 'my-irony-mode-hook)
    (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options))

  (use-package company-irony
      :straight t
      :after (company irony)
      :config
      (add-hook 'irony-mode-hook 'company-irony-setup-begin-commands)
      (setq company-backends (delete 'company-semantic company-backends))
      (eval-after-load 'company
	'(add-to-list
	  'company-backends 'company-irony)))
#+end_src 
* Report Debug Before ORG                                          :noexport:
Print Debug markers in *messages*
#+BEGIN_SRC emacs-lisp  :eval never-export
(message "Debug Before ORG")
#+END_SRC
 
* load GTD
#+BEGIN_SRC emacs-lisp
(load (expand-file-name "org-init" user-emacs-directory))
#+END_SRC
* OpenOffice export
#+begin_src emacs-lisp :tangle no
        (use-package ox-odt
        :straight (org-mode-ox-odt
                   :host github
                   :repo "kjambunathan/org-mode-ox-odt"
                   :files ("lisp/ox-odt.el"
                           "lisp/ox-ods.el"
                           "lisp/odt.el"
                           "etc"
                           "docs"
                           "contrib/odt/LibreOffice")))
#+end_src

Note that all items between the open and the close are added to the config.


* shcmd option :noexport:
This is done in the separate Org-Config.org
#+begin_src emacs-lisp :tangle no
  (error "Duplicate shcdmo code!")
  (use-package org-mode
    :straight nil
    :config
  (require 'ob-sh)
  (defadvice org-babel-sh-evaluate (around set-shell activate)
    "Add header argument :shcmd that determines the shell to be called."
    (let* ((org-babel-sh-command (or (cdr (assoc :shcmd params)) org-babel-sh-command)))
      ad-do-it
      )))
#+end_src
* Adjust for better GC
#+begin_src emacs-lisp
(setq gc-cons-threshold (* 2 1000 1000))  
#+end_src
* Report Debug END                                                 :noexport:
Print Debug markers in *messages*
#+BEGIN_SRC emacs-lisp  :eval never-export
(message "Debug END")
#+END_SRC
 
* Test for init.el completion
Clear to during init flag.
#+begin_src emacs-lisp
  (setq twr/init-loading-flag nil)
  (message "<<<<  !!!     INIT.EL FINISHED   !!!   >>>>> ")
#+end_src
* Load config
#+begin_src emacs-lisp
(load "~/.emacs-local")
#+end_src

